# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright (c) 2026 Zaheer Sheriff K
"""The Riva-compatible gRPC ``StreamingRecognize`` subset.

Protos are vendored verbatim (MIT) from ``nvidia-riva/common`` at the pinned SHA
recorded in ``proto/riva/UPSTREAM``; stubs are generated by
``scripts/gen_protos.sh`` into ``_gen/`` and committed, so users never run protoc.
"""
