#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright (c) 2026 Zaheer Sheriff K
#
# Regenerate the Riva gRPC stubs from the vendored protos.
#
#   scripts/gen_protos.sh
#
# Input:  proto/riva/proto/*.proto          (vendored verbatim, MIT, pinned -- see proto/riva/UPSTREAM)
# Output: src/verbatim/protocols/riva/_gen/ (committed, so users never run protoc)
#
# The generated tree mirrors the proto package path `riva/proto/`, because the
# descriptors register those file paths and protoc emits absolute imports for
# them. A `_gen/riva/proto/` package with __init__.py files at each level makes
# `from riva.proto import riva_audio_pb2` resolvable when `_gen/` is on the path,
# which is what the generated modules ask for.
#
# CI reruns this script and fails on any diff, so the committed stubs cannot
# drift from the committed protos.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROTO_ROOT="${REPO_ROOT}/proto"
OUT_DIR="${REPO_ROOT}/src/verbatim/protocols/riva/_gen"

PROTOS=(
  "riva/proto/riva_common.proto"
  "riva/proto/riva_audio.proto"
  "riva/proto/riva_asr.proto"
)

PYTHON="${PYTHON:-python3}"

if ! "${PYTHON}" -c "import grpc_tools.protoc" >/dev/null 2>&1; then
  echo "error: grpcio-tools is not installed in ${PYTHON}." >&2
  echo "       pip install -e '.[dev]'   (or: pip install grpcio-tools)" >&2
  exit 1
fi

echo "==> regenerating stubs into ${OUT_DIR#"${REPO_ROOT}"/}"

# Wipe only the generated tree, never the hand-written package __init__.py.
rm -rf "${OUT_DIR}/riva"
mkdir -p "${OUT_DIR}"

"${PYTHON}" -m grpc_tools.protoc \
  --proto_path="${PROTO_ROOT}" \
  --python_out="${OUT_DIR}" \
  --pyi_out="${OUT_DIR}" \
  --grpc_python_out="${OUT_DIR}" \
  "${PROTOS[@]}"

# protoc creates riva/ and riva/proto/ as plain directories. Make them packages
# so the absolute imports inside the generated modules resolve.
for pkg in "${OUT_DIR}/riva" "${OUT_DIR}/riva/proto"; do
  cat > "${pkg}/__init__.py" <<'PY'
# SPDX-License-Identifier: Apache-2.0
"""Generated by scripts/gen_protos.sh. Do not edit."""
PY
done

echo "==> generated:"
find "${OUT_DIR}/riva" -type f | sort | sed "s|^${REPO_ROOT}/|    |"

echo "==> verifying the stubs import"
PYTHONPATH="${OUT_DIR}" "${PYTHON}" - <<'PY'
from riva.proto import riva_asr_pb2, riva_asr_pb2_grpc, riva_audio_pb2, riva_common_pb2

assert riva_asr_pb2.DESCRIPTOR.package == "nvidia.riva.asr"
assert riva_audio_pb2.AudioEncoding.Name(1) == "LINEAR_PCM"
assert riva_common_pb2.RequestId(value="x").value == "x"
service = riva_asr_pb2.DESCRIPTOR.services_by_name["RivaSpeechRecognition"]
rpcs = sorted(m.name for m in service.methods)
assert rpcs == [
    "GetRivaSpeechRecognitionConfig",
    "Recognize",
    "StreamingRecognize",
], rpcs
assert hasattr(riva_asr_pb2_grpc, "RivaSpeechRecognitionServicer")
print("    ok: nvidia.riva.asr.RivaSpeechRecognition ->", ", ".join(rpcs))
PY

echo "==> done. Commit the regenerated stubs in the same change as any proto move."
